In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib notebook

In [2]:
url = "https://raw.githubusercontent.com/ga-students/SF-DAT-20/master/Data/myopia.csv"
MyopiaData = pd.read_csv(url)

In [3]:
MyopiaData.head()

ID  STUDYYEAR  MYOPIC  AGE  GENDER  SPHEQ     AL    ACD     LT    VCD  \
0   1       1992       1    6       1 -0.052  21.89  3.690  3.498  14.70   
1   2       1995       0    6       1  0.608  22.38  3.702  3.392  15.29   
2   3       1991       0    6       1  1.179  22.49  3.462  3.514  15.52   
3   4       1990       1    6       1  0.525  22.20  3.862  3.612  14.73   
4   5       1995       0    5       0  0.697  23.29  3.676  3.454  16.16   

   SPORTHR  READHR  COMPHR  STUDYHR  TVHR  DIOPTERHR  MOMMY  DADMY  
0       45       8       0        0    10         34      1      1  
1        4       0       1        1     7         12      1      1  
2       14       0       2        0    10         14      0      0  
3       18      11       0        0     4         37      0      1  
4       14       0       0        0     4          4      1      0

Here is our dataset dictionary: https://www.umass.edu/statdata/statdata/data/myopia.pdf

#### We are interested in finding out what contributes to Myopia the most. My grandmother always told me not to watch TV, play with computer since it will affect my eyes. (She was strangely find with studying!). It sounds like Drs share the same point of view with my grandmother " http://www.allaboutvision.com/conditions/myopia.htm "

#### We are DataScientist and don't trust our grandmothers or DRs unless we find the same result! Now, let's go and explore Myopia!




In [4]:
# Year of study and id should not affect anything so we disregard them in this study. 
# we consider two types of inputs - first all general inputs - i.e. physical and external inputs
# second only external inputs
X1 = MyopiaData[['SPHEQ','AL','ACD','LT','VCD','AGE','GENDER','SPORTHR','READHR','COMPHR','STUDYHR','TVHR','DIOPTERHR','MOMMY','DADMY']]
X2 = MyopiaData[['AGE','GENDER','SPORTHR','READHR','COMPHR','STUDYHR','TVHR','DIOPTERHR','MOMMY','DADMY']]
y = MyopiaData['MYOPIC']


Run your regression line on X1 and interpret your MOMMY AND DADMY coefficients.

In [25]:
lm = LogisticRegression()
lm.fit(X1,y)
lm.coef_


array([[-3.39425429,  0.11608482,  0.7725705 , -0.31202104, -0.32603735,
         0.00379052,  0.53625076, -0.04739603,  0.09764225,  0.05015885,
        -0.13224772, -0.00438644, -0.00788514,  0.63899595,  0.72678871]])

Interpretation: 

#### Use confusion matrix and estimate False negative rate and False positive rate

In [26]:
y_hat = lm.predict(X1)
confusion_matrix(y_hat, y)


array([[524,  53],
       [ 13,  28]])

In [22]:
print y.value_counts()
print "FPR:", float(13)/(13+28), " FNR:", float(53)/(53+524)

0    537
1     81
Name: MYOPIC, dtype: int64
FPR: 0.317073170732  FNR: 0.0918544194107


#### Use 10-fold cross-validation to measure accuracy of your predictions

In [17]:
from sklearn.cross_validation import cross_val_score
print(cross_val_score(lm,X1,y,cv=10).mean()) 
MisClassificationError = 1 - (cross_val_score(lm,X1,y,cv=10).mean())
print(MisClassificationError)  

0.886747164933
0.113252835067


#### In your dataset, what percentage of cases are myopic?

In [19]:
y.mean()

0.13106796116504854

#### Based on the result you found above, is your prediction precision good or bad?

Answer: Not great

#### Imagine you would like to decrease your False negative rate. What can you do in order to make it less than 2%? 

In [ ]:
change the threshold

Answer: 

#### Now let's run a logistic regression line on X2 and see if we can confirm our Grandmothers' claims!

In [23]:
lm.fit(X2,y)
print lm.coef_
y_hat = lm.predict(X2)
print confusion_matrix(y, y_hat)
from sklearn.cross_validation import cross_val_score
print(cross_val_score(lm,X2,y,cv=10).mean()) 
MisClassificationError = 1 - (cross_val_score(lm,X2,y,cv=10).mean())
print(MisClassificationError)  
# X2 = MyopiaData[['AGE','GENDER','SPORTHR','READHR','COMPHR','STUDYHR','TVHR','DIOPTERHR','MOMMY','DADMY']]



[[-0.14479354  0.2454158  -0.04711947  0.06879678  0.00937054 -0.07157385
  -0.0036419   0.00676797  0.72828899  0.83081071]]
[[537   0]
 [ 81   0]]
0.86895066858
0.13104933142


Interpret your results specifically on StudyHr, TVH, and COMPHR, Gender: Females are 25% more likely to be myopic, Study, and TV users have lower chance of being myopic, whereas readers and computer users are more likely to be myopic.

#### Now it's time for regularization and choosing the best predictors:

In [ ]:
#Let's first standardize our data - use X1
  

In [ ]:
# Try testing and plot using different C as input and l1 penalty


In [ ]:
# localize your search around the maximum value you found earlier


In [ ]:
# List your variables from the smallest to the largets


#### What is your conclusions about your Grandmothers' and some other Drs' claims?

Answer: 

#### Draw ROC curve for your best tuned model. 