In [4]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer


df3=pd.read_csv('pupfile_ready402.xls','\t') 
print df3.batch.count()
dummy_ac=pd.get_dummies(df3.Age_Cat, prefix='agecat')
print dummy_ac.describe()
del dummy_ac['agecat_Baby']
df3 = df3.join(dummy_ac)


df3['shortlist'] = [1 if x<40 else 0 for x in df3['days_on_site']]
print df3['shortlist'].describe()

6695
       agecat_Adult  agecat_Baby  agecat_Senior  agecat_Young
count   6695.000000  6695.000000    6695.000000   6695.000000
mean       0.497386     0.123226       0.082599      0.296789
std        0.500031     0.328721       0.275296      0.456877
min        0.000000     0.000000       0.000000      0.000000
25%        0.000000     0.000000       0.000000      0.000000
50%        0.000000     0.000000       0.000000      0.000000
75%        1.000000     0.000000       0.000000      1.000000
max        1.000000     1.000000       1.000000      1.000000
count    6695.000000
mean        0.924720
std         0.263862
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: shortlist, dtype: float64


In [19]:
df3['Posted Date'].unique()

array(['2016-04-02', '2016-03-29', '2016-03-19', '2016-03-18',
       '2016-03-08', '2016-03-07', '2016-03-06', '2016-03-05',
       '2016-03-03', '2016-03-02', '2016-03-01', '2016-02-29',
       '2016-02-28', '2016-02-27', '2016-02-25', '2016-02-24',
       '2016-02-23', '2016-02-22', '2016-02-21', '2016-02-20',
       '2016-02-19', '2016-02-18', '2016-02-17', '2016-02-16',
       '2016-02-15', '2016-02-14', '2016-02-13', '2016-02-12',
       '2016-02-11', '2016-02-10', '2016-02-09', '2016-02-08',
       '2016-02-07', '2016-02-06', '2016-02-05', '2016-02-04',
       '2016-02-03', '2016-02-02', '2016-02-01', '2016-01-31',
       '2016-01-30', '2016-01-29', '2016-01-28', '2016-01-27',
       '2016-01-25', '2016-01-24', '2016-01-23', '2016-01-22',
       '2016-01-21', '2016-01-20', '2016-01-19', '2016-01-18',
       '2016-01-17', '2016-01-16', '2016-01-15', '2016-01-14',
       '2016-01-13', '2016-01-12', '2016-01-11', '2016-01-10',
       '2016-01-09', '2016-01-08', '2016-01-07', '2016-

In [20]:
count_vect = CountVectorizer(stop_words='english', max_features=20)
tfid_vect = TfidfVectorizer(stop_words='english', max_features=20)
cv_breed_words = count_vect.fit_transform(df3['Breed']).toarray()
tf_breed_words = tfid_vect.fit_transform(df3['Breed']).toarray()

print cv_breed_words.shape
print tf_breed_words.shape
print tfid_vect.get_feature_names()

bw=pd.DataFrame(data=cv_breed_words, columns=count_vect.get_feature_names())
df3=df3.join(bw)


(6695, 20)
(6695, 20)
[u'american', u'australian', u'boxer', u'bull', u'bulldog', u'chihuahua', u'dachshund', u'dog', u'german', u'labrador', u'miniature', u'mix', u'mutt', u'pit', u'poodle', u'retriever', u'shepherd', u'staffordshire', u'terrier', u'unknown']


In [21]:
df3=df3[df3.Description.notnull()]


count_vect = CountVectorizer(stop_words='english',  max_df=1)
tfid_vect = TfidfVectorizer(stop_words='english', max_df=1)
cv_desc_words = count_vect.fit_transform(df3['Description']).toarray()
tf_desc_words = tfid_vect.fit_transform(df3['Description']).toarray()
print cv_desc_words.shape
print tf_desc_words.shape

(5458, 4844)
(5458, 4844)


In [22]:
print count_vect.get_feature_names()
print tfid_vect.get_feature_names()

[u'0006b71b82', u'0051', u'0071', u'0096', u'00buddy', u'00mia', u'00nina', u'00pm', u'00pmclosed', u'00pmsat', u'00sadie', u'00senior', u'01', u'02', u'0225', u'0225follow', u'0237', u'0255', u'0262', u'0316', u'0321', u'0335', u'0344', u'04', u'0494', u'0495', u'050', u'0518', u'0551', u'0554', u'0555', u'0567', u'06', u'06042015f', u'0610', u'0642', u'07', u'0765', u'08', u'0805', u'0811', u'0842', u'0871', u'09', u'0945', u'0dldi9ki83a', u'0frwb0szyd4', u'0hv4qsr81te', u'0p_rq4', u'0tqqhn', u'1000', u'100all', u'100lbs', u'100we', u'100x', u'101', u'10152482435663246', u'103', u'105', u'1065', u'1068', u'107', u'1073741832', u'1073741871', u'1073741959', u'1073742005', u'1073742123', u'1073742254', u'1073742263', u'1073742264', u'1073742267', u'1073742357', u'1080', u'1084227654935068', u'108fixed', u'109', u'10909', u'10lb', u'10lbs', u'10th', u'10yrs', u'10\xe3\xe2', u'110', u'11011', u'1102', u'1104', u'1112', u'11157', u'1131', u'11361', u'11430', u'1144', u'11602', u'116604454

In [51]:
#df3.columns.values
Z=df3[['age','sentiment','days_on_site']]
Z=Z[Z.age.notnull()]
Z.head()
y=Z.days_on_site
X=Z[['age','sentiment']]


In [53]:
from sklearn import linear_model
import random
from sklearn import feature_selection
import statsmodels.formula.api as smf
from sklearn import metrics

lm_lasso = linear_model.Lasso().fit(X,y)
lm_lasso.coef_

array([ 1.24043982,  0.        ])

In [57]:
#df3.columns.values
df3['sense']=[1 if x<.5 else 0 for x in df3['sentiment']]
Z=df3[['agecat_Adult','agecat_Young', 'agecat_Senior','sentiment','days_on_site']]
#Z=Z[Z.age.notnull()]
Z.head()
y=Z.days_on_site
X=Z[['agecat_Adult','agecat_Young', 'agecat_Senior','sentiment']]


In [56]:
lm_lasso = linear_model.Lasso().fit(X,y) # age and days on sites
lm_lasso.coef_

array([ 0.52648045, -0.15293499,  4.70833262, -0.        ])

In [62]:
y=df3.sense
X=Z[['agecat_Adult','agecat_Young', 'agecat_Senior']]



In [63]:
lm_lasso = linear_model.Lasso().fit(X,y) # age and sense
lm_lasso.coef_

array([ 0., -0.,  0.])

In [64]:
lm_lasso = linear_model.LogisticRegression().fit(X,y) # age and sense
lm_lasso.coef_

array([[ 0.92571993,  0.60994401,  0.73832682]])